- hosts: workers
  remote_user: root
  tasks:
  - name: Install pip on workers
    apt: name=python-pip state=latest

  - name: Install virtualenv and virtualenvwrapper
    shell: pip install virtualenv virtualenvwrapper

  - name: Making interns virtualenv
    shell: export WORKON_HOME=~/VEnvs && echo "export WORKON_HOME=~/VEnvs" >> .bashrc && mkdir -p $WORKON_HOME && source virtualenvwrapper.sh && mkvirtualenv interns && echo "source virtualenvwrapper.sh" >> .bashrc
    remote_user: interns
    args:
      executable: /bin/bash
