- name: Setup api-db service requirements
  hosts: api-db
  remote_user: root
  roles:
  - supervisor
  - virtualenv
  - postgresql
  - aquatic_group
  tasks:
  - name: Include aquatic vars
    include_vars: 'aquatic_vars.yml'

  - name: Add local network access auth to postgres
    lineinfile: dest=/etc/postgresql/9.4/main/pg_hba.conf regexp="^host\W+all\W+all\W+{{ ip_routing_prefix }}/24\W+md5$" insertafter="^# IPv4 local.+" line="host     all             all            {{ ip_routing_prefix }}/24          md5"

  - name: Create eleanor postgres user
    postgresql_user: name=eleanor password="md52378aac29dd2e61695dfc3db0fdf528e" encrypted=yes
    sudo: yes
    sudo_user: postgres

  - name: Create eleanor database
    postgresql_db: name=eleanor owner=eleanor
    sudo: yes
    sudo_user: postgres

  - name: Copy postgresql conf
    copy: src=postgres_configs/postgresql.conf dest=/etc/postgresql/9.4/main/postgresql.conf owner=postgres group=postgres mode=640

  - name: Restart postgres
    service: name=postgresql state=restarted

- name: Setup eleanor service requirements
  hosts: eleanor-service
  remote_user: root
  roles:
  - virtualenv
  - supervisor
  - aquatic_group
  - aquatic_service_client
  tasks:
  - name: Create user eleanor
    user: name=eleanor shell=/bin/bash password=$6$Noqb1/cqYh$GslCHsq9IpFZUGMXI4isCTySVGtUXdVJrU2oIQlfznSm33eykkpiwbGCaGHFTFZxR6prrx.gf7uflWcbnxb/v1 group=aquatic generate_ssh_key=yes

  - name: Create logging directory for eleanor service
    file: path=/var/log/eleanor state=directory owner=eleanor group=aquatic

  - name: Copy supervisor conf for service 
    copy: src=service_management/eleanor.conf dest=/etc/supervisor/conf.d/eleanor.conf owner=root group=root mode=644

  - name: Allow eleanor to manage it's service
    lineinfile: dest=/etc/sudoers regexp="^%eleanor\s+ALL=\s+NOPASSWD:\s+/usr/bin/supervisorctl$" line="%eleanor ALL= NOPASSWD{{ ':' }} /usr/bin/supervisorctl"

  - name: Reread new supervisor config
    command: supervisorctl reread

  - name: Reload supervisor
    command: supervisorctl reload
