- name: Setup interns-service service requirements
  hosts: rabbitmq-host
  remote_user: root
  tasks:
  - name: Install rabbitmq
    apt: name=rabbitmq-server state=latest update_cache=yes

- hosts: interns-service
  remote_user: root
  roles:
  - virtualenv
  - supervisor
  - aquatic_group
  - diamond
  tasks:
  - name: Create interns user
    user: name=interns shell=/bin/bash password=$6$X65HxwxncnLq2u$7RU2FxqQFVPcmTT0ubNvNZTewEUORB1xT4lnmx/7dLn7rG54N6QmZdP5.mJKSain6L1xwCzoc.XyP79uGcxo.1 group=aquatic generate_ssh_key=yes

  - name: Copy supervisor conf for interns-service
    copy: src=service_management/interns.conf dest=/etc/supervisor/conf.d/interns.conf owner=root group=root mode=644

  - name: Allow interns to manage its service
    lineinfile: dest=/etc/sudoers regexp="^%interns\s+ALL=\s+NOPASSWD:\s+/usr/bin/supervisorctl$" line="%interns ALL= NOPASSWD{{ ':' }} /usr/bin/supervisorctl"

  - name: Reload new supervisor config
    command: supervisorctl reread

  - name: Create logging directory for interns-service
    file: path=/var/log/interns-service state=directory owner=interns group=aquatic

  - name: Create logging directory for interns-scheduler
    file: path=/var/log/interns-scheduler state=directory owner=interns group=aquatic

  - name: Copy diamond interns twitter timeline conf
    copy: src=diamond/configs/InternsTwitterTimeline.conf dest=/etc/diamond/collectors/InternsTwitterTimelineCollector.conf owner=oseary group=aquatic mode=644
 
  - name: Copy diamond InternsTwitterTimeline collector
    copy: src=diamond/collectors/InternsTwitterTimeline.py dest=/usr/share/diamond/collectors/InternsTwitterTimelineCollector.py owner=oseary group=aquatic mode=644

- name: Setup interns-scheduler service requirements                                 
  hosts: rabbitmq-host                                                             
  remote_user: root                                                                
  tasks:                                                                           
  - name: Install rabbitmq                                                         
    apt: name=rabbitmq-server state=latest update_cache=yes 

- hosts: interns-scheduler
  remote_user: root
  roles:
  - virtualenv
  - supervisor
  - aquatic_group
  - diamond
  tasks:
  - name: Create interns user
    user: name=interns shell=/bin/bash password=$6$X65HxwxncnLq2u$7RU2FxqQFVPcmTT0ubNvNZTewEUORB1xT4lnmx/7dLn7rG54N6QmZdP5.mJKSain6L1xwCzoc.XyP79uGcxo.1 group=aquatic generate_ssh_key=yes

  - name: Copy supervisor conf for interns-scheduler service
    copy: src=service_management/interns-scheduler.conf dest=/etc/supervisor/conf.d/interns-scheduler.conf owner=root group=root mode=644

  - name: Allow interns to manage its service
    lineinfile: dest=/etc/sudoers regexp="^%interns\s+ALL=\s+NOPASSWD:\s+/usr/bin/supervisorctl$" line="%interns ALL= NOPASSWD{{ ':' }} /usr/bin/supervisorctl"

  - name: Reload new supervisor config
    command: supervisorctl reread

  - name: Create logging directory for interns-scheduler
    file: path=/var/log/interns-scheduler state=directory owner=interns group=aquatic

  - name: Create logging directory for interns-service
    file: path=/var/log/interns-service state=directory owner=interns group=aquatic

  - name: Copy diamond interns twitter limits conf
    copy: src=diamond/configs/InternsTwitterLimits.conf dest=/etc/diamond/collectors/InternsTwitterLimitsCollector.conf owner=oseary group=aquatic mode=644

  - name: Copy diamond InternsTwitterLimits collector
    copy: src=diamond/collectors/InternsTwitterLimits.py dest=/usr/share/diamond/collectors/InternsTwitterLimitsCollector.py owner=oseary group=aquatic mode=644
