- hosts: interns-twitter
  remote_user: root
  roles:
  - virtualenv
  - supervisor
  - aquatic_group
  - diamond
  - aquatic_service_client
  tasks:
  - name: Install python-dev
    apt: name=python-dev state=latest

  - name: Create interns user
    user: name=interns shell=/bin/bash password=$6$X65HxwxncnLq2u$7RU2FxqQFVPcmTT0ubNvNZTewEUORB1xT4lnmx/7dLn7rG54N6QmZdP5.mJKSain6L1xwCzoc.XyP79uGcxo.1 group=aquatic generate_ssh_key=yes

  - name: Copy supervisor conf for interns-service
    copy: src=service_management/interns-twitter.conf dest=/etc/supervisor/conf.d/interns-twitter.conf owner=root group=root mode=644

  - name: Allow interns to manage its service
    lineinfile: dest=/etc/sudoers regexp="^%interns\s+ALL=\s+NOPASSWD:\s+/usr/bin/supervisorctl$" line="%interns ALL= NOPASSWD{{ ':' }} /usr/bin/supervisorctl"

  - name: Create logging directory for interns-service
    file: path=/var/log/interns-twitter state=directory owner=interns group=aquatic

  - name: Install pytz for interns diamond collector
    pip: name=pytz

  - name: Copy diamond interns twitter timeline conf
    copy: src=diamond/configs/InternsTwitterTimelineCollector.conf dest=/etc/diamond/collectors/InternsTwitterTimelineCollector.conf owner=oseary group=aquatic mode=644
 
  - name: Copy diamond InternsTwitterTimeline collector
    copy: src=diamond/collectors/InternsTwitterTimelineCollector.py dest=/usr/share/diamond/collectors/InternsTwitterTimelineCollector.py owner=oseary group=aquatic mode=644

  - name: Reread new supervisor config
    command: supervisorctl reread

  - name: Reload supervisor
    command: supervisorctl reload
