- hosts: jenkins
  remote_user: root
  roles:
  - virtualenv
  - jenkins

- hosts: jenkins-worker
  remote_user: root
  roles:
  - virtualenv
  - jenkins
  tasks:
    - name: Add jenkins parent ssh key to child
      authorized_key:
        user: jenkins
        key: "{{ lookup('file', 'var/lib/jenkins/.ssh/id_rsa.pub') }}"
