- hosts: jenkins
  remote_user: root
  roles:
  - virtualenv
  - jenkins
  - node
  tasks:
  - name: Add pypi user to pypidist group
    user: name=pypi groups=pypidist append=yes

  - name: Create armhf build directory
    file: path=/var/lib/jenkins/armhf_build state=directory owner=jenkins group=jenkins

  - name: Create eleanor armhf build directory
    file: path=/var/lib/jenkins/armhf_build/eleanor state=directory owner=jenkins group=jenkins

  - name: Copy eleanor armhf build script
    copy: src=jenkins/eleanor_armhf_repo.sh dest=/var/lib/jenkins/armhf_build/eleanor/eleanor_armhf_repo.sh owner=jenkins group=jenkins mode=774

  - name: Create interns armhf build directory
    file: path=/var/lib/jenkins/armhf_build/interns state=directory owner=jenkins group=jenkins

  - name: Copy interns armhf build script
    copy: src=jenkins/interns_armhf_repo.sh dest=/var/lib/jenkins/armhf_build/interns/interns_armhf_repo.sh owner=jenkins group=jenkins mode=774

  - name: Create steve-zissou armhf build directory
    file: path=/var/lib/jenkins/armhf_build/steve-zissou state=directory owner=jenkins group=jenkins

  - name: Copy steve-zissou armhf build script
    copy: src=jenkins/steve-zissou_armhf_repo.sh dest=/var/lib/jenkins/armhf_build/steve-zissou/steve-zissou_armhf_repo.sh owner=jenkins group=jenkins mode=774

- hosts: jenkins-worker
  remote_user: root
  roles:
  - virtualenv
  - jenkins
  tasks:
    - name: Create jenkins user
      user: name=jenkins groups=pypidist append=yes shell=/bin/bash generate_ssh_key=yes

    - name: Create build directory
      file: path=/home/jenkins/builds state=directory owner=jenkins group=jenkins

    - name: Add jenkins parent ssh key to child
      authorized_key:
        user: jenkins
        key: "{{ lookup('file', '/var/lib/jenkins/.ssh/id_rsa.pub') }}"

    - name: Create jenkins child build directory
      file: path=/home/jenkins/builds state=directory owner=jenkins group=jenkins

    - name: Install openjdk-7-jdk on jenkins child node
      apt: name=openjdk-7-jdk state=latest

    - name: Install openjdk-7-jre on jenkins child node
      apt: name=openjdk-7-jre state=latest
