- name: Setup oseary service requirements
  hosts: oseary-service
  remote_user: root
  roles:
  - virtualenv
  - supervisor
  - aquatic_group
  tasks:
  - name: Create user oseary
    user: name=oseary shell=/bin/bash password=$6$0AI7khXlSjnM1f$MnTDDOM4Zmh.XE9jltaZdciB4QkdeBZD5AYTjGaZBL6sYWaFXd9.t/L1sMkzoceYz5d5NjNRVzhFqfGrSTmY20 group=aquatic generate_ssh_key=yes

  - name: Copy supervisor conf for service
    copy: src=service_management/oseary.conf dest=/etc/supervisor/conf.d/oseary.conf owner=root group=root mode=644

  - name: Allow oseary to manage its service
    lineinfile: dest=/etc/sudoers regexp="^%oseary\s+ALL=\s+NOPASSWD:\s+/usr/bin/supervisorctl$" line="%oseary ALL= NOPASSWD{{ ':' }} /usr/bin/supervisorctl"
  
  - name: Reload new supervisor config
    command: supervisorctl reread

