- name: Setup pypi requirements
  hosts: pypi
  remote_user: root
  roles:
  - virtualenv
  - supervisor
  - aquatic_group
  tasks:
    - name: Create pypi user 
      user: name=pypi shell=/bin/bash password=$6$DBtSvjmleXIAU2$aRN/hE18IMlv2/q4xtwzmulcwa9aXeEqYsBpXSTvOHRGOKfAO9IxzZeZWtcUAPH4Dg9uolExCqzL9azEAJaOF. group=aquatic generate_ssh_key=yes

    - name: Create pypi working directory
      file: path=/opt/pypi/venv owner=pypi group=aquatic state=directory


    - name: Create pypi virtualenv
      command: virtualenv /opt/pypi/venv

    - name: Install pypi in virtualenv
      pip: name=pypi virtualenv=/opt/pypi/venv

    - name: Copy supervisor conf for pypi
      copy: src=service_management/pypiserver.conf dest=/etc/supervisor/conf.d/pypiserver.conf owner=root group=root mode=644

    - name: Reload new supervisor config
      command: supervisorctl reread
