- name: Setup steve-zissou service requirements
  hosts: steve-zissou-service
  remote_user: root
  roles:
  - virtualenv
  - supervisor
  - aquatic_group
  tasks:
  - name: Include vars
    include_vars: 'aquatic_vars.yml'

  - name: Create user steve-zissou
    user: name=steve-zissou shell=/bin/bash password=$6$Noqb1/cqYh$GslCHsq9IpFZUGMXI4isCTySVGtUXdVJrU2oIQlfznSm33eykkpiwbGCaGHFTFZxR6prrx.gf7uflWcbnxb/v1 group=aquatic generate_ssh_key=yes

  - name: Create logging directory for steve-zissou service
    file: path=/var/log/steve-zissou state=directory owner=steve-zissou group=aquatic

  - name: Copy supervisor conf for service
    copy: src=service_management/steve-zissou.conf dest=/etc/supervisor/conf.d/steve-zissou.conf owner=root group=root mode=644

  - name: Allow steve-zissou to manage it's service
    lineinfile: dest=/etc/sudoers regexp="^%steve-zissou\s+ALL=\s+NOPASSWD:\s+/usr/bin/supervisorctl$" line="%steve-zissou ALL= NOPASSWD{{ ':' }} /usr/bin/supervisorctl"

  - name: Create templates directory for steve-zissou
    file: path=/opt/steve-zissou/templates/ state=directory owner=steve-zissou group=aquatic

  - name: Create static directory for steve-zissou
    file: path=/opt/steve-zissou/static/ state=directory owner=steve-zissou group=aquatic

  - name: Reread new supervisor config
    command: supervisorctl reread

  - name: Reload supervisor
    command: supervisorctl reload

  - name: Copy nginx steve-zissou configs
    copy: src=nginx_configs/steve-zissou dest=/etc/nginx/sites-available/steve-zissou

  - name: Check to see if defauly ngninx config is in place
    stat: path=/etc/nginx/sites-enabled/default
    register: default_nginx

  - name: Remove nginx defauly config if present
    file: path=/etc/nginx/sites-enabled/default state=absent
    when: default_nginx.stat.exists

  - name: Symlink nginx steve_zissou configs
    file: src=/etc/nginx/sites-available/steve-zissou dest=/etc/nginx/sites-enabled/steve-zissou state=link

  - name: Reload nginx
    service: name=nginx state=reloaded
