- name: Update to latest version of eleanor
  hosts: eleanor-service
  remote_user: root
  tasks:
  - name: Updating eleanor to the latest version
    apt: name=eleanor state=latest update_cache=yes allow_unauthenticated=yes
