- name: Update to latest version of steve-zissou
  hosts: steve-zissou-service
  remote_user: jenkins
  tasks:
  - name: Install steve_zissou_static dependencies
    shell: npm install
    environment:
      PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v6.9.1/bin"
    args:
      chdir: "{{ playbook_dir }}/steve_zissou_static/"

  - name: Build steve_zissou static assets
    shell: ./build_prod_assets.sh
    environment:
      PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v6.9.1/bin"
    args:
      chdir: "{{ playbook_dir }}/steve_zissou_static/"

- name: Update to latest version of steve-zissou
  hosts: steve-zissou-service
  remote_user: root
  tasks:
  - name: Updating apt
    apt: update_cache=yes

  - name: Updating steve-zissou to the latest version
    command: apt-get --allow-unauthenticated install steve-zissou

  - name: Move built javascript for steve-zissou
    copy: src=steve_zissou_static/build/js/ dest=/opt/steve-zissou/static/js/ owner=steve-zissou group=aquatic

  - name: Move css for steve-zissou
    copy: src=steve_zissou_static/css/ dest=/opt/steve-zissou/static/css/ owner=steve-zissou group=aquatic

  - name: Move fonts for steve-zissou
    copy: src=steve_zissou_static/fonts/ dest=/opt/steve-zissou/static/fonts/ owner=steve-zissou group=aquatic

  - name: Move templates for steve-zissou
    copy: src=steve_zissou/steve_zissou/templates/ dest=/opt/steve-zissou/templates/ owner=steve-zissou group=aquatic
