- name: Update to latest version of eleanor
  hosts: eleanor-service
  remote_user: root
  tasks:
  - name: Updating apt
    apt: update_cache=yes
  - name: Updating eleanor to the latest version
    command: apt-get --allow-unauthenticated install eleanor
