- name: Update to latest version of eleanor
  hosts: steve-zissou-service
  remote_user: root
  tasks:
  - name: Updating apt
    apt: update_cache=yes
  - name: Updating steve-zissou to the latest version
    command: apt-get --allow-unauthenticated install steve-zissou
