- name: Setup aptly
  hosts: aptly
  remote_user: root
  tasks:
  - name: Update apt and install nginx
    apt: update_cache=yes name=nginx state=present

  - name: Install aptly
    commad: apt-get --allow-unauthenticated install aptly

  - name: Copy nginx configs to sites-available
    copy: src=nginx_configs/aptly dest=/etc/nginx/sites-available/aptly

  - name: Symlink nginx configs to sites-enabled
    file: src=/etc/nginx/sites-available/aptly dest=/etc/nginx/sites-enabled/aptly state=link

  - name: Reload nginx configs
    command: service nginx reload
