- name: Create user oseary                                                    
  user: name=oseary shell=/bin/bash password=$6$0AI7khXlSjnM1f$MnTDDOM4Zmh.XE9jltaZdciB4QkdeBZD5AYTjGaZBL6sYWaFXd9.t/L1sMkzoceYz5d5NjNRVzhFqfGrSTmY20 group=aquatic generate_ssh_key=yes 
- name: Install python-pip
  apt: name=python-pip state=latest update_cache=yes

- name: Install diamond
  pip: name=diamond

- name: Create directory for diamond modules                                     
  file: path=/usr/share/diamond/collectors state=directory owner=oseary group=aquatic

- name: Create directory for diamond confs
  file: path=/etc/diamond/collectors state=directory owner=oseary group=aquatic

- name: Copy diamond.conf
  copy: src=../../../diamond/configs/diamond.conf dest=/etc/diamond/diamond.conf owner=oseary group=aquatic mode=644

- name: Copy diamond cpu conf
  copy: src=../../../diamond/configs/CPUCollector.conf dest=/etc/diamond/collectors/CPUCollector.conf owner=oseary group=aquatic mode=644

- name: Copy diamond disk space conf
  copy: src=../../../diamond/configs/DiskSpaceCollector.conf dest=/etc/diamond/collectors/DiskSpaceCollector.conf owner=oseary group=aquatic mode=644

- name: Copy diamond disk usage conf
  copy: src=../../../diamond/configs/DiskUsageCollector.conf dest=/etc/diamond/collectors/DiskUsageCollector.conf owner=oseary group=aquatic mode=644

- name: Copy diamond load conf
  copy: src=../../../diamond/configs/LoadAverageCollector.conf dest=/etc/diamond/collectors/LoadAverageCollector.conf owner=oseary group=aquatic mode=644

- name: Copy diamond  conf
  copy: src=../../../diamond/configs/MemoryCollector.conf dest=/etc/diamond/collectors/MemoryCollector.conf owner=oseary group=aquatic mode=644

- name: Copy diamond cpu collector
  copy: src=../../../diamond/collectors/cpu.py dest=/usr/share/diamond/collectors/cpu.py owner=oseary group=aquatic mode=644

- name: Copy diamond diskspace collector
  copy: src=../../../diamond/collectors/diskspace.py dest=/usr/share/diamond/collectors/diskspace.py owner=oseary group=aquatic mode=644

- name: Copy diamond diskusage collector
  copy: src=../../../diamond/collectors/diskusage.py dest=/usr/share/diamond/collectors/diskusage.py owner=oseary group=aquatic mode=644

- name: Copy diamond loadavg collector
  copy: src=../../../diamond/collectors/loadavg.py  dest=/usr/share/diamond/collectors/loadavg.py owner=oseary group=aquatic mode=644

- name: Copy diamond memory collector
  copy: src=../../../diamond/collectors/memory.py dest=/usr/share/diamond/collectors/memory.py owner=oseary group=aquatic mode=644
