- name: Create user oseary                                                    
  user: name=oseary shell=/bin/bash password=$6$0AI7khXlSjnM1f$MnTDDOM4Zmh.XE9jltaZdciB4QkdeBZD5AYTjGaZBL6sYWaFXd9.t/L1sMkzoceYz5d5NjNRVzhFqfGrSTmY20 group=aquatic generate_ssh_key=yes 
- name: Install python-pip
  apt: name=python-pip state=latest update_cache=yes

- name: Install diamond
  pip: name=diamond

- name: Create directory for diamond modules                                     
  file: path=/usr/share/diamond/collectors state=directory owner=oseary group=aquatic

- name: Create directory for diamond confs
  file: path=/etc/diamond/collectors state=directory owner=oseary group=aquatic
