- name: Restart the eleanor service
  hosts: eleanor-service
  remote_user: eleanor
  tasks:
    - name: Restart eleanor
      supervisorctl: name=eleanor state=stopped
    - name: Restart eleanor
      supervisorctl: name=eleanor state=started
