- name: Restart the interns-twitter service
  hosts: interns-twitter
  remote_user: interns
  tasks:
    - name: Stop interns
      supervisorctl: name=interns-twitter state=stopped
    - name: Restart interns
      supervisorctl: name=interns-twitter state=started
