- name: Restart the eleanor service
  hosts: steve-zissou-service
  remote_user: steve-zissou
  tasks:
    - name: Stop steve-zissou
      supervisorctl: name=steve-zissou state=stopped
    - name: Restart steve-zissou
      supervisorctl: name=steve-zissou state=started
