- name: Add aquatic user group for services to execute on
  group: name=aquatic

- name: Setup supervisor.conf to allow aquatic group to control services
  copy: src=../../../service_management/supervisor.conf dest=/etc/supervisor/supervisor.conf owner=root group=root mode=644

- name: Setup supervisord.conf to allow aquatic group to control services
  copy: src=../../../service_management/supervisor.conf dest=/etc/supervisor/supervisord.conf owner=root group=root mode=644

- name: Add sources for the aquatic services
  copy: src=../../../aquatic_sources/aptly.list dest=/etc/apt/sources.list.d/aptly.list owner=root group=root mode=644

- name: Add pubkey for aquatice services
  apt_key: data="{{ lookup('file', '../../../aquatic_sources/pubkey.asc') }}" state=present
